[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["yutanov <utanov@gmail.com>"]
packages = [
	{ include = "page_loader" },
]


[tool.poetry.dependencies]
python = "^3.8.10"
bs4 = "^0.0.1"
requests = "^2.26.0"
pytest = "^6.2.5"
progress = "^1.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
page-loader = "page_loader.scripts.page_loader:main"
